server:
  port: 1111
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  application:
    name: STOCK-PRICE-API